### ISSUE TITLE
Tilesheet Processing and Splitting into Textures

### ISSUE THREAD

**Issue by williamsuttondev** [williamsuttondev/LOS-SFML#2]
Create a functionality to take in a tilesheet image and split it into a list of sf::Textures, each of a specified size (e.g., 45x45 pixels).
Requirements:

    Tilesheet Input:
        Accept a tilesheet image as input.
    Splitting Functionality:
        Split the tilesheet into equal-sized parts based on the given dimensions (e.g., 45x45 pixels).
    Output Textures:
        Return a list of sf::Textures containing each split part of the tilesheet.

Details:

    Function or Method:
        Implement a function or method to handle the splitting process.
        Parameters should include the tilesheet image and the size of each tile (width and height).

    Image Handling:
        Use SFML (sf::Texture and sf::Image) to load and manipulate the tilesheet image.
        Ensure proper handling of image boundaries to avoid errors if the image dimensions are not a perfect multiple of the tile size.

    Texture Creation:
        Create sf::Texture objects for each split part of the tilesheet.
        Store each texture in a list to be returned by the function.

Example Usage:

```cpp
std::vector<sf::Texture> splitTilesheet(const sf::Image& tilesheet, int tileWidth, int tileHeight);
```

Acceptance Criteria:

    The function correctly splits a tilesheet image into equal-sized tiles based on the given dimensions.
    Each tile is stored as an sf::Texture in a list.
    Proper error handling for cases where the tilesheet dimensions are not a perfect multiple of the tile size.
    Thorough testing with various tilesheet sizes and tile dimensions to ensure robustness.

Additional Notes:

    Consider edge cases where the tilesheet dimensions do not divide evenly by the tile size.
    Ensure efficient memory management to avoid leaks when creating multiple sf::Texture objects.
    Provide documentation and usage examples for the implemented function

**Comment by Barnold8** [comment]
Functionality complete to basic needs. Could throw errors in the cases where width and height dont divide naturally into the tilesheet. Could also add a base x and y parameter optionally to anchor origin points of each tile.
